#ifndef EXAR_DEF_HPP
#define EXAR_DEF_HPP

#define DECLARE_EXAR_HANDLE(name) typedef struct name##_ *name;

namespace Exar {
	DECLARE_EXAR_HANDLE(MemoryHandle);
	DECLARE_EXAR_HANDLE(Surface);
	DECLARE_EXAR_HANDLE(Image);

#define EXAR_NULL_HANDLE nullptr

	enum class ExarResult
	{
		EXAR_SUCCESS = 0,
		EXAR_NULL_POINTER,

		EXAR_ERROR_INVALID_ARG,

		EXAR_ERROR_RESOURCES_LOST,

		EXAR_ERROR_MEMORY_MAP_FAILED,
		EXAR_ERROR_MEMORY_OVER_FLOW,

		EXAR_ERROR_ALLOCATOR_NULL_POINTER,
	};
}

#endif // EXAR_DEF_HPP
